name: flutter_website
publish_to: none
description: The flutter.dev website rebuilt in Flutter.
version: 2.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.3+2
  universal_html: ^2.2.4
  google_fonts: ^6.2.1
  universal_io: ^2.2.2
  responsive_framework: ^1.5.1
#  responsive_framework:
#    path: responsive_framework/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_italic.ttf
          style: italic
