// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7pr29VLmatlf7KUwRJ4tc00e-Vpi0CRE',
    appId: '1:734062564522:web:3fbc5e730d423cad7facd3',
    messagingSenderId: '734062564522',
    projectId: 'target100-f19be',
    authDomain: 'target100-f19be.firebaseapp.com',
    databaseURL: 'https://target100-f19be-default-rtdb.firebaseio.com',
    storageBucket: 'target100-f19be.firebasestorage.app',
    measurementId: 'G-PPZ66521W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdHSOdvbHMPTyNOB0bf7eHJ9W-pYSweo',
    appId: '1:734062564522:android:793ba64fc8a5aa577facd3',
    messagingSenderId: '734062564522',
    projectId: 'target100-f19be',
    databaseURL: 'https://target100-f19be-default-rtdb.firebaseio.com',
    storageBucket: 'target100-f19be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALupPVM-5xIwxIoUsIRU5Lm9_w9JXTKnc',
    appId: '1:686982146038:ios:ccdd96eb6e5d17a76f89d7',
    messagingSenderId: '686982146038',
    projectId: 'knseducation-29f8d',
    storageBucket: 'knseducation-29f8d.firebasestorage.app',
    iosBundleId: 'com.flutterWebsite',
  );
}