// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBodAef-HEegUOFhZi1pSHWaCzMCeObQJc',
    appId: '1:686982146038:web:32c44a97189f65106f89d7',
    messagingSenderId: '686982146038',
    projectId: 'knseducation-29f8d',
    authDomain: 'knseducation-29f8d.firebaseapp.com',
    storageBucket: 'knseducation-29f8d.firebasestorage.app',
    measurementId: 'G-BL8BJPPDXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUb7_Rjo3-rVCVV7laJccPzJGZwSPnTw',
    appId: '1:686982146038:android:e32887d344a0c6446f89d7',
    messagingSenderId: '686982146038',
    projectId: 'knseducation-29f8d',
    storageBucket: 'knseducation-29f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALupPVM-5xIwxIoUsIRU5Lm9_w9JXTKnc',
    appId: '1:686982146038:ios:ccdd96eb6e5d17a76f89d7',
    messagingSenderId: '686982146038',
    projectId: 'knseducation-29f8d',
    storageBucket: 'knseducation-29f8d.firebasestorage.app',
    iosBundleId: 'com.flutterWebsite',
  );
}
